Update exercise_workflow.yaml

diff --git a/.github/workflows/exercise_workflow.yaml b/.github/workflows/exercise_workflow.yaml
--- a/.github/workflows/exercise_workflow.yaml
+++ b/.github/workflows/exercise_workflow.yaml
@@ -14,3 +14,8 @@ jobs:
         run: ./gradlew test
       - name: Integ tests
         run: ./gradlew integTest
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/**/*.xml'
